### ISSUE TITLE
Checklist for hyperfine 1.0

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hyperfine#52]
A few things that I would like to do before releasing version 1.0:

- [x] Merge #53 
- [x] Merge #51 
- [x] Add a chapter about the export options in the "Usage" section in the README. Possibly show a Markdown table example. Possibly refer to the `plot_benchmark_results.py` script.
- [x] Add a chapter about parameterized benchmarks.

Usual release checklist

- [x] Update README (features, usage, ..).
- [x] Optional: update dependencies with `cargo update`.
- [x] `rustup default nightly` and `cargo clippy`
- [x] `cargo fmt`
- [x] `cargo test`
- [x] `cargo install -f`
- [x] Update version in `Cargo.toml`. Run `cargo build` to update `Cargo.lock`
- [x] `cargo publish --dry-run --allow-dirty`.
- [x] check if Travis & AppVeyor succeed
- [x] `git tag vX.Y.Z; git push --tags`
- [x] write GitHub release notes
- [x] check binaries (that were uploaded via Travis/AppVeyor)
- [x] publish to crates.io by cloning a fresh repo and calling `cargo publish`.
- [x] Flag `hyperfine` package as "out of date": https://aur.archlinux.org/packages/hyperfine/
- [ ] Optional: updated demo video

**Comment by stevepentland** [comment]
Please update reference to #50 to #53

**Comment by sharkdp** [comment]
Fixed. Thanks.

Actually, I think we could also call this release 1.0. The main benchmarking functionality seems to be quite stable. Also, it's not like its particularly important to always be downwards-compatible (which means there is no harm in bumping the major version). @stevepentland what do you think?

**Comment by stevepentland** [comment]
From where I'm standing that seems like a good idea. The entire core seems to be present, with exporting, comparisons, and so on. The only thing I'd like to consider prior to the major bump is the last comment I made on #19 that was in relation to making an option to set environment variables on the child processes. There may be some merit in giving users the ability to specify this.
